### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lilcsz** [Mr4FX/Hulk-ddos-attack#1]
C:\Users\MNT>cd C:\Users\MNT\Desktop\Hulk-ddos-attack-master

C:\Users\MNT\Desktop\Hulk-ddos-attack-master>python hulk.py
  File "hulk.py", line 14358
    headers_useragents.append('Lynx/2.8.5rel.5 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.7d')
                                                                                          ^
TabError: inconsistent use of tabs and spaces in indentation

C:\Users\MNT\Desktop\Hulk-ddos-attack-master>

**Comment by kanakapalli** [comment]
this is fake scripts.

**Comment by lilcsz** [comment]
what do you mean?

**Comment by Sheikh786aks** [comment]
It is not working when try this it is not working the server of website is
not going down

**Comment by kanakapalli** [comment]
it is showing a error

**Comment by Hyperclaw79** [comment]
This seems to be a pretty old code meant for Python 2.7.
For a robust, fast and an actual DDoS (this one is a DoS but doesn't have a botnet), try my [Asynchronous Hulk v3](https://github.com/Hyperclaw79/HULK-v3) meant for Python3.

**Comment by kanakapalli** [comment]
> This seems to be a pretty old code meant for Python 2.7.
> For a robust, fast and an actual DDoS (this one is a DoS but doesn't have a botnet), try my [Asynchronous Hulk v3](https://github.com/Hyperclaw79/HULK-v3) meant for Python3.

I'll check it out

**Comment by Miche21** [comment]
well its works on weak websites i tried it to disable my school website and it wroks prefectly

**Comment by lilcsz** [comment]
idiots install python2

**Comment by Mr4FX** [comment]
hello,
make sure that you read Requirements
and the script will work very good if you use in a VPS
